# Change these first
owner: devJasonClarke # Your GitHub organization or username, where this repository lives
repo: status-Jamaica-housing # The name of this repository

sites:
  - name: Real Estate JA
    url: https://jamaican-housing.pages.dev/


assignees: devJasonClarke

status-website:
  theme: light
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /status-Jamaica-housing
  name: Real Estate JA
  # baseUrl: /your-repo-name
  logoUrl: https://www.countryflags.io/jm/flat/64.png
  faviconSvg: https://www.countryflags.io/jm/flat/32.png
  introTitle: "Uptime Monitor for Real Estate JA"
  navbar:
    - title: Status
      href: //Real Estate JA/
    - title: Jamaica Housing
      href: https://jamaican-housing.pages.dev/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration